#!/usr/bin/env bash
# Official profile: profiles/qwen27b/fast/fp8/int8kv-256K-mtp3-text-only.env
set -euo pipefail
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

MODEL_HOST_DIR="${1:-${MODEL_HOST_DIR:-}}"
ROUTE_ID="qwen27b-fp8-int8kv-256k-mtp3-fast"
PROFILE_REF="profiles/qwen27b/fast/fp8/int8kv-256K-mtp3-text-only.env"
SERVED_NAME="${SERVED_NAME:-qwen27b-fp8-int8kv-256K-mtp3-text-only-cu128}"
MODE="${MODE:-fast}"
MODEL_FAMILY="qwen"
MODEL_VARIANT="fp8"
QUANTIZATION="${QUANTIZATION:-fp8}"
KV_CACHE_DTYPE="${KV_CACHE_DTYPE:-int8_per_token_head}"
MAX_MODEL_LEN="${MAX_MODEL_LEN:-262144}"
GPU_UTIL="${GPU_UTIL:-0.958}"
MAX_BATCHED_TOKENS="${MAX_BATCHED_TOKENS:-2048}"
MAX_NUM_SEQS="${MAX_NUM_SEQS:-1}"
MTP_K="${MTP_K:-3}"
LANGUAGE_MODEL_ONLY="${LANGUAGE_MODEL_ONLY:-1}"
SKIP_MM_PROFILING="${SKIP_MM_PROFILING:-1}"
DISABLE_CUSTOM_ALL_REDUCE="${DISABLE_CUSTOM_ALL_REDUCE:-1}"
VLLM_QWOPUS_MTP_BF16_DRAFT="${VLLM_QWOPUS_MTP_BF16_DRAFT:-1}"
VLLM_INT8KV_FA_PREFILL="${VLLM_INT8KV_FA_PREFILL:-1}"
VLLM_INT8KV_FA_CONTINUATION_DEQUANT="${VLLM_INT8KV_FA_CONTINUATION_DEQUANT:-1}"
VLLM_INT8KV_FA_CASCADE_DEQUANT="${VLLM_INT8KV_FA_CASCADE_DEQUANT:-1}"
VLLM_INT8KV_FA_CASCADE_TILE_TOKENS="${VLLM_INT8KV_FA_CASCADE_TILE_TOKENS:-65536}"

source "$SCRIPT_DIR/run-api-qwen27b-common.sh"
